version: '3.8'

services:
  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:v2.6.1
    ports:
      - 8000:8000
    entrypoint:
      - /surreal
      - start
      - --user
      - root
      - --pass
      - root

  keycloak:
    container_name: keycloak
    build: infrastructure/keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KC_REALM_NAME: learn-sec
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 8888:8080

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025